language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
env:
  - TEST_GROUP=generic
  - TEST_GROUP=pebble
  - TEST_GROUP=boulder
sudo: required
dist: bionic
install:
  - tests/scripts/setup-${TEST_GROUP}.sh
  - pip install -r requirements.txt
services:
  - docker
script:
  - tests/scripts/pytest-${TEST_GROUP}.sh
  - tests/integration/register.sh ${TEST_GROUP}
  - tests/integration/gencert.py ${TEST_GROUP}
after_script: tests/scripts/logs-${TEST_GROUP}.sh
jobs:
  include:
    - stage: deploy
      services: []
      script: echo Deploy
      python: 3.8
      deploy:
        provider: pypi
        user: __token__
        password:
          secure: M2KowFO0aKl9nrQgphTp4qDDwJgEXl5sl9sY1tzTn0TQ8fagcFrAx6r8GnnDslG07iuf45+PJ7Lzo+ydT18qjt/VmrD7czOh2pKHO5fmntgCC5Zbeved2xOnEZWf/wg7S0HKieUm3w1FGsaCoipyLP01K8CWxDjU9d3lEv0s9BESL8RKUj4oY4E3GUfuntPnXJl0FZOy/Cz0Ze67HbizMIqedZL3aNQgfWcI64/U6TcZGb2dYEKsvympXQxwhXQ6KQaWht6vm7oxYOhdAGg7qSRVdQTZHhOXwLNr3cjjRvtPc3eIPcrAq4kk4WzlCv9LUZvFpDg+iSulL9kbu3QMvHpEz0wYFmSOhcRvcV6n3Iw3dLZkLsATJvOpyBwP5HlBYB4HbTi/VTn2MiNQms5peM47sw7OWwUzkO5koLHXB72F4zaNlZqNqIYsiVc2GmBgx4Cgfs5W/XsQ1rNNJPjsRbBmDJXQPJ+xxrIV0PBfedyaG2RU0wjDHzHkj9+LYlUlEQ3vR9NHTRj8Iy+rYH298T5FxSdg7D1k6IN+gAeQnIW2ShmLnPNtv5QaFW/9Ll2Nbw7LgEGffsvjbk/AuK1Z0/KVBojF7MBhgY5ToyBfkpY2wCH2Cq4i7TXE/YyvFXkvOdCeTKbubTjb7RH68rptQU4jcmokPybupVuqrVpi/Ns=
        on:
          tags: true
          contition: '"${TRAVIS_TAG:0:1}" = "v"'
