language: python
python:
# other versions will be active later
#  - '3.3'
#  - '3.4'
  - '3.5'
sudo: required
dist: trusty
script: py.test
after_install:
  - sudo tests/scripts/setup-dependencies.sh
  - tests/scripts/setup-boulder.sh
after_script: cat ~/build/go//src/github.com/letsencrypt/boulder/nohup.out
