language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
sudo: required
dist: trusty
install:
  - sudo tests/scripts/setup-dependencies.sh
  - tests/scripts/setup-boulder.sh
  - pip install -r requirements.txt
script:
  - py.test
  - tests/integration/register.sh
  - tests/integration/gencert.py
after_script: cat ~/build/go//src/github.com/letsencrypt/boulder/nohup.out
