language: python
python:
#  - '3.3'
#  - '3.4'
  - '3.5'
sudo: required
dist: trusty
install:
  - sudo tests/scripts/setup-dependencies.sh
  - tests/scripts/setup-boulder.sh
  - pip install -r requirements.txt
services:
  - rabbitmq
script:
  - pytest --tb=line
  #- tests/integration/register.sh
  #- tests/integration/gencert.py
after_script: cat ~/build/go/src/github.com/letsencrypt/boulder/nohup.out
deploy:
  provider: pypi
  user: mswart
  password:
    secure: P0/BaZAXMv4/qhUICgXIWGD2+DZNKOE6WxBoz6Sui27FFe1VPJ6NoEPzJyHfcKovpwpApbTumsQPbpkym1azSRoneEd5KytLHZMf2TKcmZpQ5muCMwI8vLlROMnhME49eK/c2QNy9pcTD+JQmqwCqwDI0EjuclZWIt8hTqWcScq9EoDqhQ0hpV+DfPnEWWi2lQxD1ycwwIn00JE4WNKdIw+W+Q0Upup5RTADaeeeRPX3ZxNYpvcKSG0bDX2Q2drs//35SiVsZENg0GZ1bS0tpYBzUVXeAgsOIaqvN33DMNDVOh5+GZlVX5l0MK/hzqPOihEP06BKGn+Nx/oWLP01XRCRrG7NHohyUqkUbz5cPlPC/kN6kh42AVhi4JOOzFuihSZzGeVdsGj0CNzUgY9IcXMFTUOQM5hL3zZxYxMv8lAN9RSHfcRw3cZ+UesIHeC3piDxVQ68vaBZDSdmJjbir766ddGSAg0uIy55/64UOpF6HUzMcfAvnbdNywFdSEH5R+W7CwoWdF7GDAB7cY/aKs14JgYOkHdBtUaWy4XiE5LuD4ZMW/xyfkbc89WkxI+dDFPEzYnWZL2oQGvGtAwVlVcn3Ylp9IINtB1iO+r3UwPaKQzbr3s3R2jzzKVfjZkNiXzFhgDyYOpWReT7vL7Ga6TpSuFrLnSmksnZf8rRyqo=
  on:
    tags: true
    contition: '"${TRAVIS_TAG:0:1}" = "v"'
    python: "3.5"
