#!/bin/sh

set -e


case "$1" in
    configure)
        if ! getent passwd acmems > /dev/null; then
            adduser --quiet --system --group --no-create-home --home /var/lib/acmems acmems
        fi
        chown acmems:acmems /var/lib/acmems /var/log/acmems
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
